### Import Libraries and Data Exploration

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder

from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier

from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [4]:
car_insurance_fraud_df = pd.read_csv(r'car_insurance_fraud_dataset.csv')
car_insurance_fraud_df_copy = car_insurance_fraud_df.copy(deep=True)
car_insurance_fraud_df_copy.shape

(30000, 24)

In [5]:
pd.set_option('display.max_columns', 24)
car_insurance_fraud_df_copy.head()

,policy_id,policy_state,policy_deductible,policy_annual_premium,insured_age,insured_sex,insured_education_level,insured_occupation,insured_hobbies,incident_date,incident_type,collision_type,incident_severity,authorities_contacted,incident_state,incident_city,incident_hour_of_the_day,number_of_vehicles_involved,bodily_injuries,witnesses,police_report_available,claim_amount,total_claim_amount,fraud_reported
0,POL100000,GA,400,1430.78,74,OTHER,High School,Manager,reading,2024-06-13,Parked Car,Front,Total Loss,NaN,MI,Charlesville,6,1,4,0,Yes,8161.36,11677.60,Y
1,POL100001,PA,300,854.49,74,MALE,College,Lawyer,chess,2025-03-23,Vehicle Theft,Rear,Total Loss,NaN,OH,Joshuaberg,0,3,4,5,No,18561.79,18027.81,N
2,POL100002,MI,400,1247.28,28,OTHER,PhD,Doctor,reading,2025-01-26,Parked Car,Unknown,Total Loss,Police,MI,Reynoldsfurt,14,4,4,1,No,10734.61,10375.59,N
3,POL100003,CA,600,622.42,37,MALE,PhD,Teacher,yachting,2024-06-03,Parked Car,Rear,Total Loss,Police,NC,Josephchester,22,3,3,5,No,13188.92,14204.34,N
4,POL100004,MI,700,1458.17,31,OTHER,PhD,Sales,reading,2024-05-21,Single Vehicle Collision,Side,Minor Damage,Fire,NY,Caitlinfort,18,4,2,4,No,21864.69,24038.84,N

In [6]:
car_insurance_fraud_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   policy_id                    30000 non-null  object
 1   policy_state                 30000 non-null  object
 2   policy_deductible            30000 non-null  int64
 3   policy_annual_premium        30000 non-null  float64
 4   insured_age                  30000 non-null  int64
 5   insured_sex                  30000 non-null  object
 6   insured_education_level      30000 non-null  object
 7   insured_occupation           30000 non-null  object
 8   insured_hobbies              30000 non-null  object
 9   incident_date                30000 non-null  object
 10  incident_type                30000 non-null  object
 11  collision_type               30000 non-null  object
 12  incident_severity            30000 non-null  object
 13  authorities_contacted        22436 non-null  object
 14  incident_state               30000 non-null  object
 15  incident_city                30000 non-null  object
 16  incident_hour_of_the_day     30000 non-null  int64
 17  number_of_vehicles_involved  30000 non-null  int64
 18  bodily_injuries              30000 non-null  int64
 19  witnesses                    30000 non-null  int64
 20  police_report_available      30000 non-null  object
 21  claim_amount                 30000 non-null  float64
 22  total_claim_amount           30000 non-null  float64
 23  fraud_reported               30000 non-null  object
dtypes: float64(3), int64(6), object(15)
memory usage: 5.5+ MB

In [7]:
car_insurance_fraud_df.describe().T

,count,mean,std,min,25%,50%,75%,max
policy_deductible,30000.0,562.783333,250.413012,200.00,300.0000,600.000,800.0000,1000.00
policy_annual_premium,30000.0,1051.255214,260.357163,600.02,826.3200,1051.155,1277.9025,1499.98
insured_age,30000.0,46.500133,16.707778,18.00,32.0000,46.000,61.0000,75.00
incident_hour_of_the_day,30000.0,11.505000,6.896155,0.00,6.0000,12.000,17.0000,23.00
number_of_vehicles_involved,30000.0,2.508933,1.116555,1.00,2.0000,3.000,4.0000,4.00
bodily_injuries,30000.0,1.997600,1.411829,0.00,1.0000,2.000,3.0000,4.00
witnesses,30000.0,2.504667,1.707691,0.00,1.0000,2.000,4.0000,5.00
claim_amount,30000.0,10823.078981,6629.690781,266.74,5350.9475,10204.170,15381.8675,29719.87
total_claim_amount,30000.0,12757.736600,7028.920069,502.18,6685.5075,12740.430,18809.9100,24999.72